#server port
server:
  port: 9090
spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb
    username: sa
  
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp    
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: pankaj52dipu@gmail.com
    password: pankaj1995
    properties.mail.smtp:
                                auth: true 
                                starttls.enable: true
     
